<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            [
                'is_active' => 1,
                'name' => 'Kablosuz Mouse',
                'description' => '2.4Ghz USB alıcılı, 1600 DPI ergonomik mouse.',
                'barcode' => '8690000000001',
                'warranty_period' => 24,
                'list_price' => 499.90,
                'sale_price' => 399.90,
                'quantity' => 120,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Mekanik Klavye',
                'description' => 'Kırmızı switch, RGB aydınlatma, TR-Q düzen.',
                'barcode' => '8690000000002',
                'warranty_period' => 24,
                'list_price' => 1899.00,
                'sale_price' => 1699.00,
                'quantity' => 45,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => '27" IPS Monitör',
                'description' => '2K çözünürlük, 75Hz, IPS panel, ince çerçeve.',
                'barcode' => '8690000000003',
                'warranty_period' => 24,
                'list_price' => 5999.00,
                'sale_price' => 0.00,
                'quantity' => 18,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'USB-C Şarj Kablosu 1m',
                'description' => 'Örgülü, hızlı şarj destekli Type-C kablo.',
                'barcode' => '8690000000004',
                'warranty_period' => 12,
                'list_price' => 149.90,
                'sale_price' => 99.90,
                'quantity' => 300,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'USB-C Şarj Adaptörü 20W',
                'description' => 'PD destekli hızlı şarj adaptörü.',
                'barcode' => '8690000000005',
                'warranty_period' => 24,
                'list_price' => 399.90,
                'sale_price' => 349.90,
                'quantity' => 160,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'is_active' => 1,
                'name' => 'Bluetooth Kulaklık TWS',
                'description' => 'Dokunmatik kontrol, şarj kutulu, ANC destekli.',
                'barcode' => '8690000000006',
                'warranty_period' => 24,
                'list_price' => 1299.00,
                'sale_price' => 1099.00,
                'quantity' => 70,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Powerbank 10000mAh',
                'description' => 'Çift USB çıkış, Type-C giriş, hızlı şarj destekli.',
                'barcode' => '8690000000007',
                'warranty_period' => 24,
                'list_price' => 899.90,
                'sale_price' => 799.90,
                'quantity' => 95,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'HDMI Kablo 2m',
                'description' => '4K 60Hz destekli, altın uçlu HDMI kablo.',
                'barcode' => '8690000000008',
                'warranty_period' => 12,
                'list_price' => 199.90,
                'sale_price' => 0.00,
                'quantity' => 220,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Laptop Standı Alüminyum',
                'description' => 'Yüksekliği ayarlanabilir, ısı dağıtıcı tasarım.',
                'barcode' => '8690000000009',
                'warranty_period' => 12,
                'list_price' => 699.00,
                'sale_price' => 599.00,
                'quantity' => 60,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'USB Hub 4 Port',
                'description' => 'USB 3.0 destekli, 4 port çoğaltıcı.',
                'barcode' => '8690000000010',
                'warranty_period' => 24,
                'list_price' => 549.90,
                'sale_price' => 499.90,
                'quantity' => 110,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // --- 11-20 ---
            [
                'is_active' => 1,
                'name' => 'Klavye-Mouse Seti',
                'description' => 'Kablosuz, sessiz tuşlar, USB nano alıcı.',
                'barcode' => '8690000000011',
                'warranty_period' => 24,
                'list_price' => 999.00,
                'sale_price' => 899.00,
                'quantity' => 75,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Ekran Temizleme Spreyi',
                'description' => '200ml, iz bırakmayan ekran temizleyici.',
                'barcode' => '8690000000012',
                'warranty_period' => 0,
                'list_price' => 129.90,
                'sale_price' => 0.00,
                'quantity' => 250,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Ethernet Kablo Cat6 10m',
                'description' => 'Gigabit destekli, Cat6 ağ kablosu.',
                'barcode' => '8690000000013',
                'warranty_period' => 12,
                'list_price' => 249.90,
                'sale_price' => 199.90,
                'quantity' => 140,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Akıllı Priz Wi-Fi',
                'description' => 'Uygulama kontrolü, zamanlayıcı, enerji takibi.',
                'barcode' => '8690000000014',
                'warranty_period' => 24,
                'list_price' => 699.90,
                'sale_price' => 649.90,
                'quantity' => 55,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'LED Masa Lambası',
                'description' => '3 renk modu, dokunmatik kontrol, USB güç.',
                'barcode' => '8690000000015',
                'warranty_period' => 24,
                'list_price' => 899.00,
                'sale_price' => 0.00,
                'quantity' => 40,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Webcam Full HD',
                'description' => '1080p, dahili mikrofon, otomatik ışık ayarı.',
                'barcode' => '8690000000016',
                'warranty_period' => 24,
                'list_price' => 1499.00,
                'sale_price' => 1299.00,
                'quantity' => 35,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Bluetooth Hoparlör',
                'description' => 'Taşınabilir, su sıçramasına dayanıklı, 10 saat pil.',
                'barcode' => '8690000000017',
                'warranty_period' => 24,
                'list_price' => 1199.00,
                'sale_price' => 999.00,
                'quantity' => 48,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Taşınabilir SSD 1TB',
                'description' => 'USB 3.2, 1000MB/s okuma, şok dayanımı.',
                'barcode' => '8690000000018',
                'warranty_period' => 36,
                'list_price' => 4499.00,
                'sale_price' => 4299.00,
                'quantity' => 22,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Kablolu Kulaklık',
                'description' => '3.5mm jack, mikrofonlu, hafif tasarım.',
                'barcode' => '8690000000019',
                'warranty_period' => 24,
                'list_price' => 399.90,
                'sale_price' => 0.00,
                'quantity' => 130,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Type-C to HDMI Dönüştürücü',
                'description' => '4K görüntü aktarımı, tak-çalıştır adaptör.',
                'barcode' => '8690000000020',
                'warranty_period' => 24,
                'list_price' => 999.90,
                'sale_price' => 899.90,
                'quantity' => 65,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // --- 21-30 ---
            [
                'is_active' => 1,
                'name' => 'Akıllı Saat',
                'description' => 'Nabız ölçer, uyku takibi, bildirim desteği.',
                'barcode' => '8690000000021',
                'warranty_period' => 24,
                'list_price' => 2999.00,
                'sale_price' => 2799.00,
                'quantity' => 28,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Oyun Mouse Pad XL',
                'description' => 'Kaymaz taban, geniş yüzey, dikişli kenar.',
                'barcode' => '8690000000022',
                'warranty_period' => 12,
                'list_price' => 499.00,
                'sale_price' => 449.00,
                'quantity' => 90,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Kablo Düzenleyici Set',
                'description' => 'Cırt kelepçe + spiral kablo toplayıcı seti.',
                'barcode' => '8690000000023',
                'warranty_period' => 0,
                'list_price' => 149.00,
                'sale_price' => 0.00,
                'quantity' => 400,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Akıllı Ampul',
                'description' => 'Wi-Fi, 16 milyon renk, uygulama kontrolü.',
                'barcode' => '8690000000024',
                'warranty_period' => 24,
                'list_price' => 399.00,
                'sale_price' => 349.00,
                'quantity' => 150,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Telefon Tripodu',
                'description' => 'Ayarlanabilir, uzaktan kumandalı, hafif tripod.',
                'barcode' => '8690000000025',
                'warranty_period' => 12,
                'list_price' => 699.00,
                'sale_price' => 599.00,
                'quantity' => 52,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Masaüstü Mikrofon',
                'description' => 'USB bağlantı, cardioid, yayın/konferans için.',
                'barcode' => '8690000000026',
                'warranty_period' => 24,
                'list_price' => 2499.00,
                'sale_price' => 2299.00,
                'quantity' => 25,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Laptop Çantası 15.6"',
                'description' => 'Su itici kumaş, darbe emici bölme.',
                'barcode' => '8690000000027',
                'warranty_period' => 12,
                'list_price' => 1299.00,
                'sale_price' => 0.00,
                'quantity' => 70,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Akıllı Tartı',
                'description' => 'Vücut analizi, Bluetooth senkronizasyon.',
                'barcode' => '8690000000028',
                'warranty_period' => 24,
                'list_price' => 999.00,
                'sale_price' => 899.00,
                'quantity' => 44,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Air Fryer 5L',
                'description' => 'Yağsız pişirme, dijital ekran, 8 program.',
                'barcode' => '8690000000029',
                'warranty_period' => 24,
                'list_price' => 4499.00,
                'sale_price' => 3999.00,
                'quantity' => 16,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Filtre Kahve Makinesi',
                'description' => '1.25L kapasite, zamanlayıcı, sıcak tutma.',
                'barcode' => '8690000000030',
                'warranty_period' => 24,
                'list_price' => 3299.00,
                'sale_price' => 0.00,
                'quantity' => 12,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // --- 31-40 ---
            [
                'is_active' => 1,
                'name' => 'Elektrikli Süpürge',
                'description' => 'Yüksek emiş gücü, HEPA filtre, 800W.',
                'barcode' => '8690000000031',
                'warranty_period' => 24,
                'list_price' => 7999.00,
                'sale_price' => 7499.00,
                'quantity' => 10,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Blender Seti',
                'description' => 'Çok amaçlı, 1000W, doğrayıcı ve çırpıcı başlıklı.',
                'barcode' => '8690000000032',
                'warranty_period' => 24,
                'list_price' => 2999.00,
                'sale_price' => 2799.00,
                'quantity' => 20,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Şarjlı Matkap',
                'description' => '18V, çift akü, darbeli, taşıma çantalı.',
                'barcode' => '8690000000033',
                'warranty_period' => 24,
                'list_price' => 4999.00,
                'sale_price' => 4699.00,
                'quantity' => 14,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Akıllı Kapı Zili',
                'description' => 'Wi-Fi, hareket algılama, gece görüşü.',
                'barcode' => '8690000000034',
                'warranty_period' => 24,
                'list_price' => 2999.00,
                'sale_price' => 0.00,
                'quantity' => 9,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Router Wi-Fi 6',
                'description' => 'AX1800, çift bant, geniş kapsama alanı.',
                'barcode' => '8690000000035',
                'warranty_period' => 36,
                'list_price' => 3999.00,
                'sale_price' => 3699.00,
                'quantity' => 27,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Akım Korumalı Priz',
                'description' => '6’lı, aşırı gerilim koruma, anahtarlı.',
                'barcode' => '8690000000036',
                'warranty_period' => 24,
                'list_price' => 699.00,
                'sale_price' => 599.00,
                'quantity' => 85,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Ofis Sandalyesi',
                'description' => 'Ergonomik, bel destekli, nefes alır kumaş.',
                'barcode' => '8690000000037',
                'warranty_period' => 24,
                'list_price' => 6499.00,
                'sale_price' => 5999.00,
                'quantity' => 8,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Masaüstü Organizer',
                'description' => 'Metal file, kalemlik ve evrak bölmeli.',
                'barcode' => '8690000000038',
                'warranty_period' => 0,
                'list_price' => 349.00,
                'sale_price' => 0.00,
                'quantity' => 140,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Termal Macun',
                'description' => 'Yüksek iletkenlik, CPU/GPU için 4g.',
                'barcode' => '8690000000039',
                'warranty_period' => 0,
                'list_price' => 249.00,
                'sale_price' => 199.00,
                'quantity' => 200,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Klavye Bilek Desteği',
                'description' => 'Jel dolgulu, kaymaz taban, konforlu destek.',
                'barcode' => '8690000000040',
                'warranty_period' => 12,
                'list_price' => 399.00,
                'sale_price' => 0.00,
                'quantity' => 95,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // --- 41-50 ---
            [
                'is_active' => 1,
                'name' => 'Telefon Kılıfı',
                'description' => 'Darbe emici, şeffaf, sararmaya dayanıklı.',
                'barcode' => '8690000000041',
                'warranty_period' => 6,
                'list_price' => 249.90,
                'sale_price' => 199.90,
                'quantity' => 260,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Ekran Koruyucu Cam',
                'description' => '9H sertlik, tam kaplama temperli cam.',
                'barcode' => '8690000000042',
                'warranty_period' => 0,
                'list_price' => 149.90,
                'sale_price' => 0.00,
                'quantity' => 500,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Araç İçi Telefon Tutucu',
                'description' => 'Havalandırma ızgarası uyumlu, güçlü mıknatıs.',
                'barcode' => '8690000000043',
                'warranty_period' => 12,
                'list_price' => 349.90,
                'sale_price' => 299.90,
                'quantity' => 180,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Akıllı Ev Sensörü',
                'description' => 'Kapı/pencere sensörü, anlık bildirim.',
                'barcode' => '8690000000044',
                'warranty_period' => 24,
                'list_price' => 499.90,
                'sale_price' => 0.00,
                'quantity' => 77,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Elektrikli Diş Fırçası',
                'description' => '3 mod, şarj standı, 2 başlık.',
                'barcode' => '8690000000045',
                'warranty_period' => 24,
                'list_price' => 1799.00,
                'sale_price' => 1599.00,
                'quantity' => 33,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Saç Kurutma Makinesi',
                'description' => '2200W, iyon teknolojisi, 2 hız 3 ısı.',
                'barcode' => '8690000000046',
                'warranty_period' => 24,
                'list_price' => 1999.00,
                'sale_price' => 0.00,
                'quantity' => 21,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Mutfak Tartısı Dijital',
                'description' => '5kg kapasite, hassas ölçüm, dara fonksiyonu.',
                'barcode' => '8690000000047',
                'warranty_period' => 12,
                'list_price' => 499.00,
                'sale_price' => 449.00,
                'quantity' => 58,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 0,
                'name' => 'Stok Dışı Ürün (Demo)',
                'description' => 'Test amaçlı pasif ürün kaydı.',
                'barcode' => '8690000000048',
                'warranty_period' => 0,
                'list_price' => 99.00,
                'sale_price' => 0.00,
                'quantity' => 0,
                'on_sale' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Notebook Soğutucu',
                'description' => '5 fanlı, sessiz çalışma, LED aydınlatma.',
                'barcode' => '8690000000049',
                'warranty_period' => 24,
                'list_price' => 1499.00,
                'sale_price' => 1299.00,
                'quantity' => 26,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'is_active' => 1,
                'name' => 'Pratik El Aleti Seti',
                'description' => '31 parça tornavida uç seti, mıknatıslı uç.',
                'barcode' => '8690000000050',
                'warranty_period' => 24,
                'list_price' => 999.00,
                'sale_price' => 899.00,
                'quantity' => 64,
                'on_sale' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('products')->insert($rows);
    }
}
